save_data: data/onmt
src_vocab: models/multi_head_model/vocab.src
tgt_vocab: models/multi_head_model/vocab.tgt
model_type: transformer
encoder_type: transformer
decoder_type: transformer
position_encoding: true
layers: 4
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
heads: 8
attention_type: multi-head
train_steps: 500
save_model: models/multi_head_model/model